name: sonoda
version: 0.1.0.0
category: Simple
author: aiya000
maintainer: aiya000 <aiya000.develop@gmail.com>
copyright: aiya000
license: MIT
homepage: https://github.com/aiya000/hs-sonoda
description: an implementation of simply typed lambda calculus
synopsis: an implementation of simply typed lambda calculus

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-unused-do-bind
  - -Wno-orphans
  - -fprint-potential-instances
  - -fprint-explicit-kinds

dependencies:
  - base >= 4.7 && < 5
  - parsers
  - safe-exceptions
  - safe-exceptions-checked
  - text
  - trifecta
  - unordered-containers
  - utf8-string

library:
  source-dirs: src

executables:
  sonoda:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies: sonoda

tests:
  doctest:
    main: DocTest.hs
    source-dirs:
      - test/doctest
      - src
    dependencies:
      - doctest
  tasty-test:
    main: Tasty.hs
    source-dirs:
      - test/tasty
      - src
    dependencies:
      - hspec
      - hspec-expectations
      - random-names
      - smallcheck
      - tasty
      - tasty-discover
      - tasty-hspec
      - tasty-smallcheck
