name: sonoda
version: 0.1.0.0
category: Simple
author: aiya000
maintainer: aiya000 <aiya000.develop@gmail.com>
copyright: aiya000
license: MIT
homepage: https://github.com/aiya000/hs-sonoda
description: an implementation of simply typed lambda calculus
synopsis: an implementation of simply typed lambda calculus

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wno-name-shadowing
  - -Wno-orphans
  - -Wno-unused-do-bind
  - -Wredundant-constraints
  - -fprint-explicit-kinds
  - -fprint-potential-instances

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - array
  - attoparsec
  - base >= 4.7 && < 5
  - here
  - lens
  - rio
  - safe
  - safe-exceptions
  - safe-exceptions-checked
  - template-haskell
  - utf8-string

library:
  source-dirs: src
  build-tools:
    - happy

executables:
  sonoda:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies: sonoda

tests:
  doctest:
    main: DocTest.hs
    source-dirs:
      - test/doctest
      - src
    dependencies:
      - doctest
  tasty-test:
    main: Tasty.hs
    source-dirs:
      - test/tasty
      - src
    dependencies:
      - QuickCheck
      - hspec
      - hspec-expectations
      - random-names
      - smallcheck
      - tasty
      - tasty-discover
      - tasty-hspec
      - tasty-quickcheck
      - tasty-smallcheck
